#!/bin/bash

if [ ! -z $1 ]; then
    WORKDIR="$1"
    cd "$WORKDIR"
elif [ -f "$(find $PWD -type f -name $(basename $PWD))" ]; then
    WORKDIR="$PWD"
else
    echo 'Usage: pwnenv [WORKDIR]'
    exit 1
fi

BIN=$(basename $WORKDIR)

tmux new-session    -s pwn -n ncelf -d
tmux send-key       -t pwn:0 "ncelf ./$BIN" C-m
tmux new-window     -t pwn gdb "./$BIN"
tmux new-window     -t pwn vim exp.py
tmux new-window     -t pwn bash
tmux new-window     -t pwn bash
tmux new-window     -t pwn ipython
tmux split-window   -t pwn:0 -h bash
tmux split-window   -t pwn:2 -h bash
tmux select-window  -t pwn:2
tmux attach         -t pwn
