#!/bin/bash

if [ ! -z $1 ]; then
    WORKDIR="$1"
    cd "$WORKDIR"
elif [ -f "$(find $PWD -type f -name $(basename $PWD))" ]; then
    WORKDIR="$PWD"
else
    echo 'Usage: pwnenv [WORKDIR]'
    exit 1
fi

BIN=$(basename $WORKDIR)
cp ~/code/mypwn/exp.py .

screen -S pwn -d -m -t "ncat" ncgdb ./$BIN
screen -S pwn -X screen -t "gdb" gdb
screen -S pwn -X screen -t "vim" vim exp.py
screen -S pwn -X screen -t "run" bash 
screen -S pwn -X screen -t "bash" bash 
screen -S pwn -X screen -t "ipy" ipython

screen -r
