#!/bin/bash

if [ ! -z $1 ]; then
    WORKDIR="$1"
    cd "$WORKDIR"
elif [ -f "$(find $PWD -type f -name $(basename $PWD))" ]; then
    WORKDIR="$PWD"
else
    echo 'Usage: pwnenv [WORKDIR]'
    exit 1
fi

BIN=$(basename $WORKDIR)
[ -f "./exp.py" ] || cp ~/code/mypwn/exp.py .

screen -S pwn -d -m ncelf "./$BIN"
sleep 0.1
screen -S pwn -X screen -t gdb gdb "./$BIN"
screen -S pwn -X screen -t vim vim exp.py
screen -S pwn -X screen bash
screen -S pwn -X screen bash
screen -S pwn -X screen -t ipy ipython
screen -S pwn -X screen bash
screen -S pwn -X screen bash

screen -r -p 3
